apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-component-enzj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-component-enzj
    app.kubernetes.io/part-of: test-app-ljxl
  name: test-component-enzj
  namespace: build-e2e-yuit-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: test-component-enzj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: test-component-enzj
    spec:
      containers:
      - image: quay.io/susdas/test-images:726bb484c8f542d38549c171c2f81224
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
